name: validate

on:
  - push

env:
  DOTNET_VERSION: 5.0.x

jobs:
  check:
    name: Check code style
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: dotnet tool install -g dotnet-format
      - run: dotnet-format --check src/Mure.sln

  build:
    name: Build and test on .NET v${{ matrix.dotnet.version }}
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        dotnet: # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
          - version: "5.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - run: dotnet build src/Mure.sln
      - run: dotnet test src/Mure.sln
