name: validate

on:
  - pull_request
  - push

jobs:
  check:
    name: Check code style (.NET v${{ matrix.dotnet.version }})
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        dotnet: # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
          - version: "5.0"
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - run: dotnet tool install --add-source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json -g dotnet-format
      - run: dotnet-format --check Mure.sln

  build:
    name: Build and test code (.NET v${{ matrix.dotnet.version }})
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    strategy:
      matrix:
        dotnet: # https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json
          - version: "5.0"
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - run: dotnet restore Mure.sln
      - run: dotnet build Mure.sln
      - run: dotnet test Mure.Test
